"""
Genome file parsing — covers every format Gene Lens claims to support and
the synthetic fixture shipped in sample/.
"""
import gzip
from pathlib import Path

import pytest

from src.parsers import detect_format, load_genome


class TestSampleFixture:
    def test_sample_loads(self, sample_genome_path: Path):
        genome, _meta, fmt = load_genome(sample_genome_path)
        assert fmt == "genera_csv"
        assert len(genome) >= 50

    def test_sample_entries_have_expected_shape(self, sample_genome_path: Path):
        genome, _, _ = load_genome(sample_genome_path)
        for rsid, entry in list(genome.items())[:5]:
            assert rsid.startswith("rs")
            assert "chromosome" in entry
            assert "position" in entry
            assert "genotype" in entry
            assert len(entry["genotype"]) >= 2


class TestFormatDetection:
    def test_detects_23andme_by_header(self, tmp_path: Path):
        f = tmp_path / "twentythree.txt"
        f.write_text(
            "# This data file generated by 23andMe at: Mon Jan 01 2024\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs1\t1\t100\tAA\n"
        )
        assert detect_format(f) == "23andme"

    def test_detects_ancestrydna_by_header(self, tmp_path: Path):
        f = tmp_path / "ancestry.txt"
        f.write_text(
            "#AncestryDNA raw data download\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "rs1\t1\t100\tA\tA\n"
        )
        assert detect_format(f) == "ancestry"

    def test_detects_myheritage_by_header(self, tmp_path: Path):
        f = tmp_path / "myh.csv"
        f.write_text(
            "# MyHeritage DNA raw data\n"
            "RSID,CHROMOSOME,POSITION,RESULT\n"
            "rs1,1,100,AA\n"
        )
        assert detect_format(f) == "myheritage"

    def test_detects_genera_csv_by_rsid_column(self, tmp_path: Path):
        f = tmp_path / "genera.csv"
        f.write_text("RSID,CHROMOSOME,POSITION,RESULT\nrs1,1,100,AA\n")
        assert detect_format(f) == "genera_csv"


class TestGzipSupport:
    def test_loads_gzipped_csv(self, tmp_path: Path, sample_genome_path: Path):
        gz_path = tmp_path / "sample.csv.gz"
        with gzip.open(gz_path, "wt") as out:
            out.write(sample_genome_path.read_text())

        genome, _, fmt = load_genome(gz_path)
        assert fmt == "genera_csv"
        assert len(genome) >= 50


class TestRobustness:
    def test_skips_no_call_genotypes(self, tmp_path: Path):
        f = tmp_path / "with_nocalls.csv"
        f.write_text(
            "RSID,CHROMOSOME,POSITION,RESULT\n"
            "rs1,1,100,AA\n"
            "rs2,1,101,--\n"
            "rs3,1,102,GG\n"
        )
        genome, _, _ = load_genome(f)
        assert "rs1" in genome
        assert "rs2" not in genome
        assert "rs3" in genome

    def test_ignores_non_rs_identifiers(self, tmp_path: Path):
        f = tmp_path / "mixed.csv"
        f.write_text(
            "RSID,CHROMOSOME,POSITION,RESULT\n"
            "rs1,1,100,AA\n"
            "i12345,1,101,GG\n"
        )
        genome, _, _ = load_genome(f)
        assert "rs1" in genome
        assert "i12345" not in genome
